name: node Continuous Integration
# This workflow will be triggered when we push a commit to the repo
on: push
# Specify an array of jobs
jobs:
  build-node:
    name: Build and run Node project
    # runs-on: windows-latest
    runs-on: ubuntu-latest
    # Specify the container instance to run the workflow steps
    # container: node:17.6.0
    steps:
      # - run: node --version
      #  name: Check Node version
      # - run: npm --version
      #  name: Check npm version
      # Checkout our code into this workflow
      # https://github.com/actions/checkout
      - name: Checkout code from Github
        uses: actions/checkout@v4
      - name: Install NPM dependencies
        run: npm i
      - name: Build project assets
        run: npm run build
      - name: Run Node application
        run: npm start
      - name: Upload built JS code
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-js-code
          path: ./build