# This workflow will be triggered when we push a commit to the repo
on: push
# Specify an array of jobs
jobs:
  first-job:
    # runs-on: windows-latest
    runs-on: ubuntu-latest
    # Specify the container instance to run the workflow steps
    container: node:17.6.0
    steps:
      - run: node --version
      - run: npm --version
      # Checkout our code into this workflow
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
      - run: npm i
      - run: node index.js